### ISSUE TITLE
Change movie quote every time a command is entered

### ISSUE THREAD

**Issue by tmjoseantonio** [tmjoseantonio/random-movie-quotes#2]
Currently the movie quote + author is being the same on each terminal session. It would be awesome to have it change every time a command is entered.

**Comment by rodrigo-kondo** [comment]
could you elaborate the desired behavior

**Comment by tmjoseantonio** [comment]
Sure @rodrigo-kondo, what I want is something like this:

```
"Some movie quote" - From a movie
$ cd ..

"Another movie quote" - From another movie
$ ls

"Yet another movie quote" - From yet another movie
$ 
```

**Comment by rodrigo-kondo** [comment]
I can work on this one

**Comment by rodrigo-kondo** [comment]
srry for the delay, but it was kinda tricky finding this one
