### ISSUE TITLE
Fetch quotes and authors from API service

### ISSUE THREAD

**Issue by tmjoseantonio** [tmjoseantonio/random-movie-quotes#3]
Let's see if it's possible to use the following API for fetching quotes instead of using a static list.
https://market.mashape.com/andruxnet/random-famous-quotes

Response seem to be similar to this:
```
{
  "quote": "Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.",
  "author": "Sherlock Holmes",
  "category": "Famous",
}
```

**Comment by asi7296** [comment]
I'll take this!

**Comment by tmjoseantonio** [comment]
It is, thanks for the help

**Comment by sourav52** [comment]
Hey, It is not Open API. How we will integrate this. Mashape key is required.

**Comment by tmjoseantonio** [comment]
You're right @sourav52. lets reconsider this for now.
CC. @kritokrator
